kind: Deployment
apiVersion: apps/v1
metadata:
  name: dev_bahia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev_bahia
  template:
    metadata:
      labels:
        app: dev_bahia
    spec:
      containers:
        - name: dev_bahia
          image: localhost:5000/dev_bahia
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: dev_bahia
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: my-react-app